import { API_BASE_URL, getHeaders } from './api';

const COUPONS_API_BASE = `${API_BASE_URL}/coupons`;

// ========== VENDOR MARKETPLACE API ==========

/**
 * Get all vendors with available coupons
 */
export const getAllVendors = async (params?: {
  search?: string;
  category?: string;
  page?: number;
  limit?: number;
}) => {
  const queryParams = new URLSearchParams();
  if (params?.search) queryParams.append('search', params.search);
  if (params?.category) queryParams.append('category', params.category);
  if (params?.page) queryParams.append('page', params.page.toString());
  if (params?.limit) queryParams.append('limit', params.limit.toString());

  const response = await fetch(`${COUPONS_API_BASE}/vendors?${queryParams.toString()}`, {
    headers: getHeaders(),
  });

  if (!response.ok) throw new Error('Failed to fetch vendors');
  return response.json();
};

/**
 * Get vendor details with their approved coupons
 */
export const getVendorDetails = async (vendorId: string) => {
  const response = await fetch(`${COUPONS_API_BASE}/vendors/${vendorId}`, {
    headers: getHeaders(),
  });

  if (!response.ok) throw new Error('Failed to fetch vendor details');
  return response.json();
};

/**
 * Generate a coupon when student pays vendor
 */
export const generateStudentCoupon = async (couponData: {
  vendorId: string;
  amountPaid: number;
  offerId?: string;
  discount?: number;
  discountType?: 'percentage' | 'fixed';
  description?: string;
}) => {
  const response = await fetch(`${COUPONS_API_BASE}/generate`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify(couponData),
  });

  if (!response.ok) throw new Error('Failed to generate coupon');
  return response.json();
};

/**
 * Get all coupons generated by student
 */
export const getStudentCoupons = async (params?: {
  status?: 'active' | 'used' | 'expired';
  page?: number;
  limit?: number;
}) => {
  const queryParams = new URLSearchParams();
  if (params?.status) queryParams.append('status', params.status);
  if (params?.page) queryParams.append('page', params.page.toString());
  if (params?.limit) queryParams.append('limit', params.limit.toString());

  const response = await fetch(
    `${COUPONS_API_BASE}/student/my-coupons?${queryParams.toString()}`,
    {
      headers: getHeaders(),
    }
  );

  if (!response.ok) throw new Error('Failed to fetch student coupons');
  return response.json();
};

/**
 * Get a specific coupon by ID
 */
export const getCouponById = async (couponId: string) => {
  const response = await fetch(`${COUPONS_API_BASE}/${couponId}`, {
    headers: getHeaders(),
  });

  if (!response.ok) throw new Error('Failed to fetch coupon');
  return response.json();
};

/**
 * Purchase a coupon (from offers/coupons)
 */
export const purchaseCoupon = async (offerId: string, quantity: number = 1) => {
  const response = await fetch(`${API_BASE_URL}/coupon-purchase/buy`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify({
      offerId,
      quantity,
      transactionId: `TXN-${Date.now()}`,
      paymentMethod: 'online',
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || 'Failed to purchase coupon');
  }
  return response.json();
};

/**
 * Get student's purchased coupons
 */
export const getPurchasedCoupons = async (params?: {
  status?: 'active' | 'used' | 'expired';
  page?: number;
  limit?: number;
}) => {
  const queryParams = new URLSearchParams();
  if (params?.status) queryParams.append('status', params.status);
  if (params?.page) queryParams.append('page', params.page.toString());
  if (params?.limit) queryParams.append('limit', params.limit.toString());

  const response = await fetch(
    `${API_BASE_URL}/coupon-purchase/my-purchases?${queryParams.toString()}`,
    {
      headers: getHeaders(),
    }
  );

  if (!response.ok) throw new Error('Failed to fetch purchased coupons');
  return response.json();
};

/**
 * Get vendors with active offers/coupons
 */
export const getVendorsWithOffers = async (params?: {
  search?: string;
  page?: number;
  limit?: number;
}) => {
  const queryParams = new URLSearchParams();
  if (params?.search) queryParams.append('search', params.search);
  if (params?.page) queryParams.append('page', params.page.toString());
  if (params?.limit) queryParams.append('limit', params.limit.toString());

  const response = await fetch(
    `${API_BASE_URL}/coupon-purchase/vendors-with-offers?${queryParams.toString()}`,
    {
      headers: getHeaders(),
    }
  );

  if (!response.ok) throw new Error('Failed to fetch vendors with offers');
  return response.json();
};

/**
 * Redeem a coupon at vendor location
 */
export const redeemCoupon = async (couponCode: string, redemptionNotes?: string) => {
  const response = await fetch(`${API_BASE_URL}/coupon-purchase/validate`, {
    method: 'POST',
    headers: getHeaders(),
    body: JSON.stringify({
      couponCode,
      redemptionNotes,
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || 'Failed to redeem coupon');
  }
  return response.json();
};
